package com.mk.ots.activity.model;

import java.util.Date;

public class UActiveCDKeyLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_active_cdkey_log.id
     *
     * @mbggenerated Thu Sep 17 16:11:22 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_active_cdkey_log.mid
     *
     * @mbggenerated Thu Sep 17 16:11:22 CST 2015
     */
    private Long mid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_active_cdkey_log.code
     *
     * @mbggenerated Thu Sep 17 16:11:22 CST 2015
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_active_cdkey_log.activeid
     *
     * @mbggenerated Thu Sep 17 16:11:22 CST 2015
     */
    private Long activeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_active_cdkey_log.channelid
     *
     * @mbggenerated Thu Sep 17 16:11:22 CST 2015
     */
    private Long channelid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_active_cdkey_log.promotionid
     *
     * @mbggenerated Thu Sep 17 16:11:22 CST 2015
     */
    private Long promotionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_active_cdkey_log.success
     *
     * @mbggenerated Thu Sep 17 16:11:22 CST 2015
     */
    private Boolean success;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_active_cdkey_log.push
     *
     * @mbggenerated Thu Sep 17 16:11:22 CST 2015
     */
    private Boolean push;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_active_cdkey_log.createtime
     *
     * @mbggenerated Thu Sep 17 16:11:22 CST 2015
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_active_cdkey_log.hardwarecode
     *
     * @mbggenerated Thu Sep 17 16:11:22 CST 2015
     */
    private String hardwarecode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_active_cdkey_log.id
     *
     * @return the value of u_active_cdkey_log.id
     * @mbggenerated Thu Sep 17 16:11:22 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_active_cdkey_log.id
     *
     * @param id the value for u_active_cdkey_log.id
     * @mbggenerated Thu Sep 17 16:11:22 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_active_cdkey_log.mid
     *
     * @return the value of u_active_cdkey_log.mid
     * @mbggenerated Thu Sep 17 16:11:22 CST 2015
     */
    public Long getMid() {
        return mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_active_cdkey_log.mid
     *
     * @param mid the value for u_active_cdkey_log.mid
     * @mbggenerated Thu Sep 17 16:11:22 CST 2015
     */
    public void setMid(Long mid) {
        this.mid = mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_active_cdkey_log.code
     *
     * @return the value of u_active_cdkey_log.code
     * @mbggenerated Thu Sep 17 16:11:22 CST 2015
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_active_cdkey_log.code
     *
     * @param code the value for u_active_cdkey_log.code
     * @mbggenerated Thu Sep 17 16:11:22 CST 2015
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_active_cdkey_log.activeid
     *
     * @return the value of u_active_cdkey_log.activeid
     * @mbggenerated Thu Sep 17 16:11:22 CST 2015
     */
    public Long getActiveid() {
        return activeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_active_cdkey_log.activeid
     *
     * @param activeid the value for u_active_cdkey_log.activeid
     * @mbggenerated Thu Sep 17 16:11:22 CST 2015
     */
    public void setActiveid(Long activeid) {
        this.activeid = activeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_active_cdkey_log.channelid
     *
     * @return the value of u_active_cdkey_log.channelid
     * @mbggenerated Thu Sep 17 16:11:22 CST 2015
     */
    public Long getChannelid() {
        return channelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_active_cdkey_log.channelid
     *
     * @param channelid the value for u_active_cdkey_log.channelid
     * @mbggenerated Thu Sep 17 16:11:22 CST 2015
     */
    public void setChannelid(Long channelid) {
        this.channelid = channelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_active_cdkey_log.promotionid
     *
     * @return the value of u_active_cdkey_log.promotionid
     * @mbggenerated Thu Sep 17 16:11:22 CST 2015
     */
    public Long getPromotionid() {
        return promotionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_active_cdkey_log.promotionid
     *
     * @param promotionid the value for u_active_cdkey_log.promotionid
     * @mbggenerated Thu Sep 17 16:11:22 CST 2015
     */
    public void setPromotionid(Long promotionid) {
        this.promotionid = promotionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_active_cdkey_log.success
     *
     * @return the value of u_active_cdkey_log.success
     * @mbggenerated Thu Sep 17 16:11:22 CST 2015
     */
    public Boolean getSuccess() {
        return success;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_active_cdkey_log.success
     *
     * @param success the value for u_active_cdkey_log.success
     * @mbggenerated Thu Sep 17 16:11:22 CST 2015
     */
    public void setSuccess(boolean success) {
        this.success = success;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_active_cdkey_log.push
     *
     * @return the value of u_active_cdkey_log.push
     * @mbggenerated Thu Sep 17 16:11:22 CST 2015
     */
    public Boolean getPush() {
        return push;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_active_cdkey_log.push
     *
     * @param push the value for u_active_cdkey_log.push
     * @mbggenerated Thu Sep 17 16:11:22 CST 2015
     */
    public void setPush(Boolean push) {
        this.push = push;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_active_cdkey_log.createtime
     *
     * @return the value of u_active_cdkey_log.createtime
     * @mbggenerated Thu Sep 17 16:11:22 CST 2015
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_active_cdkey_log.createtime
     *
     * @param createtime the value for u_active_cdkey_log.createtime
     * @mbggenerated Thu Sep 17 16:11:22 CST 2015
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_active_cdkey_log.hardwarecode
     *
     * @return the value of u_active_cdkey_log.hardwarecode
     * @mbggenerated Thu Sep 17 16:11:22 CST 2015
     */
    public String getHardwarecode() {
        return hardwarecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_active_cdkey_log.hardwarecode
     *
     * @param hardwarecode the value for u_active_cdkey_log.hardwarecode
     * @mbggenerated Thu Sep 17 16:11:22 CST 2015
     */
    public void setHardwarecode(String hardwarecode) {
        this.hardwarecode = hardwarecode == null ? null : hardwarecode.trim();
    }
}