package com.mk.ots.city.model;

import java.math.BigDecimal;

public class TCityCommentConfig {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_city_comment_config.id
     *
     * @mbggenerated Sat Sep 12 13:04:44 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_city_comment_config.citycode
     *
     * @mbggenerated Sat Sep 12 13:04:44 CST 2015
     */
    private Long citycode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_city_comment_config.value
     *
     * @mbggenerated Sat Sep 12 13:04:44 CST 2015
     */
    private BigDecimal value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_city_comment_config.status
     *
     * @mbggenerated Sat Sep 12 13:04:44 CST 2015
     */
    private Boolean status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_city_comment_config.id
     *
     * @return the value of t_city_comment_config.id
     * @mbggenerated Sat Sep 12 13:04:44 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_city_comment_config.id
     *
     * @param id the value for t_city_comment_config.id
     * @mbggenerated Sat Sep 12 13:04:44 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_city_comment_config.citycode
     *
     * @return the value of t_city_comment_config.citycode
     * @mbggenerated Sat Sep 12 13:04:44 CST 2015
     */
    public Long getCitycode() {
        return citycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_city_comment_config.citycode
     *
     * @param citycode the value for t_city_comment_config.citycode
     * @mbggenerated Sat Sep 12 13:04:44 CST 2015
     */
    public void setCitycode(Long citycode) {
        this.citycode = citycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_city_comment_config.value
     *
     * @return the value of t_city_comment_config.value
     * @mbggenerated Sat Sep 12 13:04:44 CST 2015
     */
    public BigDecimal getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_city_comment_config.value
     *
     * @param value the value for t_city_comment_config.value
     * @mbggenerated Sat Sep 12 13:04:44 CST 2015
     */
    public void setValue(BigDecimal value) {
        this.value = value;
    }

    public Boolean getStatus() {
        return status;
    }

    public void setStatus(Boolean status) {
        this.status = status;
    }
}