package com.mk.ots.wallet.model;

import java.math.BigDecimal;
import java.util.Date;

public class UWallet {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_wallet.id
     *
     * @mbggenerated Wed Sep 09 15:07:34 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_wallet.mid
     *
     * @mbggenerated Wed Sep 09 15:07:34 CST 2015
     */
    private Long mid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_wallet.balance
     *
     * @mbggenerated Wed Sep 09 15:07:34 CST 2015
     */
    private BigDecimal balance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_wallet.lastmodify
     *
     * @mbggenerated Wed Sep 09 15:07:34 CST 2015
     */
    private Date lastmodify;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_wallet.id
     *
     * @return the value of u_wallet.id
     * @mbggenerated Wed Sep 09 15:07:34 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_wallet.id
     *
     * @param id the value for u_wallet.id
     * @mbggenerated Wed Sep 09 15:07:34 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_wallet.mid
     *
     * @return the value of u_wallet.mid
     * @mbggenerated Wed Sep 09 15:07:34 CST 2015
     */
    public Long getMid() {
        return mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_wallet.mid
     *
     * @param mid the value for u_wallet.mid
     * @mbggenerated Wed Sep 09 15:07:34 CST 2015
     */
    public void setMid(Long mid) {
        this.mid = mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_wallet.balance
     *
     * @return the value of u_wallet.balance
     * @mbggenerated Wed Sep 09 15:07:34 CST 2015
     */
    public BigDecimal getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_wallet.balance
     *
     * @param balance the value for u_wallet.balance
     * @mbggenerated Wed Sep 09 15:07:34 CST 2015
     */
    public void setBalance(BigDecimal balance) {
        this.balance = balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_wallet.lastmodify
     *
     * @return the value of u_wallet.lastmodify
     * @mbggenerated Wed Sep 09 15:07:34 CST 2015
     */
    public Date getLastmodify() {
        return lastmodify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_wallet.lastmodify
     *
     * @param lastmodify the value for u_wallet.lastmodify
     * @mbggenerated Wed Sep 09 15:07:34 CST 2015
     */
    public void setLastmodify(Date lastmodify) {
        this.lastmodify = lastmodify;
    }
}