package com.mk.ots.member.model;

import java.util.Date;

public class UPromotionLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_promotion_log.id
     *
     * @mbggenerated Thu Sep 17 16:52:37 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_promotion_log.mid
     *
     * @mbggenerated Thu Sep 17 16:52:37 CST 2015
     */
    private Long mid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_promotion_log.activeid
     *
     * @mbggenerated Thu Sep 17 16:52:37 CST 2015
     */
    private Long activeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_promotion_log.promoinstanceid
     *
     * @mbggenerated Thu Sep 17 16:52:37 CST 2015
     */
    private Long promoinstanceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_promotion_log.promotionid
     *
     * @mbggenerated Thu Sep 17 16:52:37 CST 2015
     */
    private Long promotionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_promotion_log.noticetype
     *
     * @mbggenerated Thu Sep 17 16:52:37 CST 2015
     */
    private String noticetype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_promotion_log.success
     *
     * @mbggenerated Thu Sep 17 16:52:37 CST 2015
     */
    private Boolean success;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_promotion_log.errormsg
     *
     * @mbggenerated Thu Sep 17 16:52:37 CST 2015
     */
    private String errormsg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_promotion_log.createtime
     *
     * @mbggenerated Thu Sep 17 16:52:37 CST 2015
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_promotion_log.hardwarecode
     *
     * @mbggenerated Thu Sep 17 16:52:37 CST 2015
     */
    private String hardwarecode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_promotion_log.id
     *
     * @return the value of u_promotion_log.id
     * @mbggenerated Thu Sep 17 16:52:37 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_promotion_log.id
     *
     * @param id the value for u_promotion_log.id
     * @mbggenerated Thu Sep 17 16:52:37 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_promotion_log.mid
     *
     * @return the value of u_promotion_log.mid
     * @mbggenerated Thu Sep 17 16:52:37 CST 2015
     */
    public Long getMid() {
        return mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_promotion_log.mid
     *
     * @param mid the value for u_promotion_log.mid
     * @mbggenerated Thu Sep 17 16:52:37 CST 2015
     */
    public void setMid(Long mid) {
        this.mid = mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_promotion_log.activeid
     *
     * @return the value of u_promotion_log.activeid
     * @mbggenerated Thu Sep 17 16:52:37 CST 2015
     */
    public Long getActiveid() {
        return activeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_promotion_log.activeid
     *
     * @param activeid the value for u_promotion_log.activeid
     * @mbggenerated Thu Sep 17 16:52:37 CST 2015
     */
    public void setActiveid(Long activeid) {
        this.activeid = activeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_promotion_log.promoinstanceid
     *
     * @return the value of u_promotion_log.promoinstanceid
     * @mbggenerated Thu Sep 17 16:52:37 CST 2015
     */
    public Long getPromoinstanceid() {
        return promoinstanceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_promotion_log.promoinstanceid
     *
     * @param promoinstanceid the value for u_promotion_log.promoinstanceid
     * @mbggenerated Thu Sep 17 16:52:37 CST 2015
     */
    public void setPromoinstanceid(Long promoinstanceid) {
        this.promoinstanceid = promoinstanceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_promotion_log.promotionid
     *
     * @return the value of u_promotion_log.promotionid
     * @mbggenerated Thu Sep 17 16:52:37 CST 2015
     */
    public Long getPromotionid() {
        return promotionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_promotion_log.promotionid
     *
     * @param promotionid the value for u_promotion_log.promotionid
     * @mbggenerated Thu Sep 17 16:52:37 CST 2015
     */
    public void setPromotionid(Long promotionid) {
        this.promotionid = promotionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_promotion_log.noticetype
     *
     * @return the value of u_promotion_log.noticetype
     * @mbggenerated Thu Sep 17 16:52:37 CST 2015
     */
    public String getNoticetype() {
        return noticetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_promotion_log.noticetype
     *
     * @param noticetype the value for u_promotion_log.noticetype
     * @mbggenerated Thu Sep 17 16:52:37 CST 2015
     */
    public void setNoticetype(String noticetype) {
        this.noticetype = noticetype == null ? null : noticetype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_promotion_log.success
     *
     * @return the value of u_promotion_log.success
     * @mbggenerated Thu Sep 17 16:52:37 CST 2015
     */
    public Boolean getSuccess() {
        return success;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_promotion_log.success
     *
     * @param success the value for u_promotion_log.success
     * @mbggenerated Thu Sep 17 16:52:37 CST 2015
     */
    public void setSuccess(Boolean success) {
        this.success = success;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_promotion_log.errormsg
     *
     * @return the value of u_promotion_log.errormsg
     * @mbggenerated Thu Sep 17 16:52:37 CST 2015
     */
    public String getErrormsg() {
        return errormsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_promotion_log.errormsg
     *
     * @param errormsg the value for u_promotion_log.errormsg
     * @mbggenerated Thu Sep 17 16:52:37 CST 2015
     */
    public void setErrormsg(String errormsg) {
        this.errormsg = errormsg == null ? null : errormsg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_promotion_log.createtime
     *
     * @return the value of u_promotion_log.createtime
     * @mbggenerated Thu Sep 17 16:52:37 CST 2015
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_promotion_log.createtime
     *
     * @param createtime the value for u_promotion_log.createtime
     * @mbggenerated Thu Sep 17 16:52:37 CST 2015
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_promotion_log.hardwarecode
     *
     * @return the value of u_promotion_log.hardwarecode
     * @mbggenerated Thu Sep 17 16:52:37 CST 2015
     */
    public String getHardwarecode() {
        return hardwarecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_promotion_log.hardwarecode
     *
     * @param hardwarecode the value for u_promotion_log.hardwarecode
     * @mbggenerated Thu Sep 17 16:52:37 CST 2015
     */
    public void setHardwarecode(String hardwarecode) {
        this.hardwarecode = hardwarecode == null ? null : hardwarecode.trim();
    }
}