/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.mk.framework.component.thrift;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum API_VERSION implements org.apache.thrift.TEnum {
  VERSION_1(0),
  VERSION_2(1);

  private final int value;

  private API_VERSION(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static API_VERSION findByValue(int value) { 
    switch (value) {
      case 0:
        return VERSION_1;
      case 1:
        return VERSION_2;
      default:
        return null;
    }
  }
}
